#!/bin/sh
# /etc/init.d/opensmtpd
#
# Written by Daniel Walrond <debian@djw.org.uk>

### BEGIN INIT INFO
# Provides:          opensmtpd
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: opensmtpd Mail Transport Agent
# Description:       OpenSMTPD
### END INIT INFO

set -ue

DAEMON="/usr/sbin/smtpd"
CONTROL="/usr/sbin/smtpctl"
PIDFILE="/run/opensmtpd.pid"

test -x /usr/sbin/smtpd || exit 0

. /lib/lsb/init-functions

smtpd_start()
{
  start-stop-daemon \
    --start \
    --exec "${DAEMON}" 
  log_progress_msg "opensmtpd"
}

smtpd_stop()
{
  "${CONTROL}" stop > /dev/null
  log_progress_msg "opensmtpd"
}

smtpd_config_check()
{
  "${DAEMON}" -n 2>/dev/null || \
    log_end_msg 1 || \
      "${DAEMON}" -n 

}

case "$1" in
  start)
    log_daemon_msg "Starting MTA"
    smtpd_config_check
    smtpd_start
    log_end_msg 0
    ;;
  stop)
    log_daemon_msg "Stopping MTA"
    smtpd_stop
    log_end_msg 0
    ;;
  restart)
    log_daemon_msg "Stopping MTA for restart"
    smtpd_config_check
    smtpd_stop
    log_end_msg 0
    log_daemon_msg "Restarting MTA"
    smtpd_start
    log_end_msg 0
    ;;
  force-reload)
    log_daemon_msg "Stopping MTA for reload"
    smtpd_stop
    log_end_msg 0
    log_daemon_msg "Restarting MTA"
    smtpd_start
    log_end_msg 0
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
